POST http://localhost:5274/api/auth/create-role

###
POST http://localhost:5274/api/auth/register
Content-Type: application/json

{
    "Username": "testuser9",
    "Email": "test1@example.com",
    "Password": "P@ssw0rd"
}

###
POST http://localhost:5274/api/auth/login
Content-Type: application/json

{
    "Username": "testuser9",
    "Password": "P@ssw0rd"
}