GET http://localhost:5274/

###
GET http://localhost:5274/api/inventory

###
GET http://localhost:5274/api/inventory/5
Cookie: .AspNetCore.Identity.Application=CfDJ8KxcMmpymXBBjG7yT-n0J0dulMIN937XHcJ7rqKFBoxDrz7saiXJtxU1DM1YfR1EjBmkK8EkQG4b9-mMvq03zXIZTiMFBaKGVQlfUkyRG51bXOidra0E1qbnE19D3SM5ae7rhz8iMcTWPH85YJ06S-kGjIUFngiNJdt7QiG1T80SqRPulAXjQX-1EETgKx_DOgDZ2RSFNrySkOfQnPzNcTGjK1MNs9kEZD3t7PI1_J5x9MS4-vfKx_Ho5VpMMtfJjkgnrxrL3E2Vv3X-Jq01Xmtc536s5dyrD5WclO8Yo9oCwt3QCpAvHu48TluVS9dH7ZD_IiWc8m59u0xCk8vEbRoNGb4F9V9OXj_YOe5SXBFzr5E5jhvWE6s6rPq8FapDnGFO9GHXmJx8CYHlreK3M-dbqT_BPH9LNHib4m4x0gppk30bIo1e4eeSjAchejra1AmY2vojcVn89ePNfe-6CfuozAeypzFUu_DvkXcNEX7BKTrLMDWUJ3jRaKZhHP075Qasww3Bcz1HcC5L5r-eJ1_ESzDL8LRPE6W87dWe6o0nOuIKkocXsoe8-nKnJfxNIX8erWQnjXHN1Up9J_hAhzZ9lTidEF-wPzS3SeYC8h1J3sedlrG4UjX-C5RJ7u7khmeopGpCtF8oISrLJTszFBckfGXQ3UFTKh5xlYQnuyhQtORwxUhtHkrbV7mO-kukJxQnPT95qo6yY6T_vXuI5eKQJaH8jK8uehx1jUCjqMVeHajzkTyA3DrOvs2KJQdDf5lWkqHgBTCZVTbigsCyFqKvLK0HlFDHYLvLY2zNUZA7CTpe330WF_dUivdC3Hm7Z7VqmGZCkwL3XFJ-5U8ASy8; path=/; samesite=lax; httponly

###
POST http://localhost:5274/api/inventory
Content-Type: application/json
Cookie: .AspNetCore.Identity.Application=CfDJ8KxcMmpymXBBjG7yT-n0J0dulMIN937XHcJ7rqKFBoxDrz7saiXJtxU1DM1YfR1EjBmkK8EkQG4b9-mMvq03zXIZTiMFBaKGVQlfUkyRG51bXOidra0E1qbnE19D3SM5ae7rhz8iMcTWPH85YJ06S-kGjIUFngiNJdt7QiG1T80SqRPulAXjQX-1EETgKx_DOgDZ2RSFNrySkOfQnPzNcTGjK1MNs9kEZD3t7PI1_J5x9MS4-vfKx_Ho5VpMMtfJjkgnrxrL3E2Vv3X-Jq01Xmtc536s5dyrD5WclO8Yo9oCwt3QCpAvHu48TluVS9dH7ZD_IiWc8m59u0xCk8vEbRoNGb4F9V9OXj_YOe5SXBFzr5E5jhvWE6s6rPq8FapDnGFO9GHXmJx8CYHlreK3M-dbqT_BPH9LNHib4m4x0gppk30bIo1e4eeSjAchejra1AmY2vojcVn89ePNfe-6CfuozAeypzFUu_DvkXcNEX7BKTrLMDWUJ3jRaKZhHP075Qasww3Bcz1HcC5L5r-eJ1_ESzDL8LRPE6W87dWe6o0nOuIKkocXsoe8-nKnJfxNIX8erWQnjXHN1Up9J_hAhzZ9lTidEF-wPzS3SeYC8h1J3sedlrG4UjX-C5RJ7u7khmeopGpCtF8oISrLJTszFBckfGXQ3UFTKh5xlYQnuyhQtORwxUhtHkrbV7mO-kukJxQnPT95qo6yY6T_vXuI5eKQJaH8jK8uehx1jUCjqMVeHajzkTyA3DrOvs2KJQdDf5lWkqHgBTCZVTbigsCyFqKvLK0HlFDHYLvLY2zNUZA7CTpe330WF_dUivdC3Hm7Z7VqmGZCkwL3XFJ-5U8ASy8; path=/; samesite=lax; httponly

{
    "itemId": 1,
    "Name": "Drill",
    "quantity": 1,
    "location": "Warehouse A"
}

###
DELETE http://localhost:5274/api/inventory/3
Cookie: .AspNetCore.Identity.Application=CfDJ8KxcMmpymXBBjG7yT-n0J0dulMIN937XHcJ7rqKFBoxDrz7saiXJtxU1DM1YfR1EjBmkK8EkQG4b9-mMvq03zXIZTiMFBaKGVQlfUkyRG51bXOidra0E1qbnE19D3SM5ae7rhz8iMcTWPH85YJ06S-kGjIUFngiNJdt7QiG1T80SqRPulAXjQX-1EETgKx_DOgDZ2RSFNrySkOfQnPzNcTGjK1MNs9kEZD3t7PI1_J5x9MS4-vfKx_Ho5VpMMtfJjkgnrxrL3E2Vv3X-Jq01Xmtc536s5dyrD5WclO8Yo9oCwt3QCpAvHu48TluVS9dH7ZD_IiWc8m59u0xCk8vEbRoNGb4F9V9OXj_YOe5SXBFzr5E5jhvWE6s6rPq8FapDnGFO9GHXmJx8CYHlreK3M-dbqT_BPH9LNHib4m4x0gppk30bIo1e4eeSjAchejra1AmY2vojcVn89ePNfe-6CfuozAeypzFUu_DvkXcNEX7BKTrLMDWUJ3jRaKZhHP075Qasww3Bcz1HcC5L5r-eJ1_ESzDL8LRPE6W87dWe6o0nOuIKkocXsoe8-nKnJfxNIX8erWQnjXHN1Up9J_hAhzZ9lTidEF-wPzS3SeYC8h1J3sedlrG4UjX-C5RJ7u7khmeopGpCtF8oISrLJTszFBckfGXQ3UFTKh5xlYQnuyhQtORwxUhtHkrbV7mO-kukJxQnPT95qo6yY6T_vXuI5eKQJaH8jK8uehx1jUCjqMVeHajzkTyA3DrOvs2KJQdDf5lWkqHgBTCZVTbigsCyFqKvLK0HlFDHYLvLY2zNUZA7CTpe330WF_dUivdC3Hm7Z7VqmGZCkwL3XFJ-5U8ASy8; path=/; samesite=lax; httponly